### ISSUE TITLE
Use gerrit.mcp as submodule instead of github.com

### ISSUE THREAD

**Issue by jason4wy** [Mirantis/stacklight-salt-model#46]
when i git cone https://github.com/Mirantis/stacklight-salt-model.git,        the submodule classes/system --- https://gerrit.mcp.mirantis.net/salt-models/reclass-system/  can not be download ,anyone know how to download this submodule?

**Comment by simonpasquier** [comment]
This submodule is in a private repository which isn't (yet) accessible to external contributors unfortunately.
